### ISSUE TITLE
Counter bug

### ISSUE THREAD

**Issue by hartpableo** [mrk-hnr/Marameo-Code_Connect3#2]
![image](https://github.com/user-attachments/assets/746045eb-ac18-4b4b-a17f-bf3f4d3c11d8)

There's an unnecessary extra 0 for 2 digit numbers.

**Comment by mrk-hnr** [comment]
Applied decimal-leading-zero to css counter
Reference: w3school

**Comment by hartpableo** [comment]
![image](https://github.com/user-attachments/assets/8a712928-e5e3-4236-b3ba-fcd003f418fb)

Label tag is not fit for this use case.

**Comment by mrk-hnr** [comment]
label tag used to minimize confusion during trial and error phase.
label changed to span and also changed the span containing the header title it to header
