### ISSUE TITLE
Anchor tags vs buttons

### ISSUE THREAD

**Issue by hartpableo** [mrk-hnr/Marameo-Code_Connect3#3]
![image](https://github.com/user-attachments/assets/2682e1a3-90cd-4dd9-8a41-46a4362887e7)

![image](https://github.com/user-attachments/assets/518b98f7-d54c-41e9-b28f-51a3b4e284cb)

Use anchor tags instead of buttons.

Buttons are commonly only used in form submit buttons and buttons with a JavaScript implementation to them.

**Comment by mrk-hnr** [comment]
button successfully changed to anchor tag
